base_url = "https://roktas.dev"      # Domain name of your website
title = "roktas"
description = "Recai Oktaş"
default_language = "tr"
output_dir = "public"
compile_sass = true
minify_html = true
build_search_index = false
generate_feed = false
feed_filename = "feed.xml"
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_themes_css = [
    { theme = "serene-light", filename = "hl-light.css"},
    { theme = "serene-dark", filename = "hl-dark.css"},
]
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]

name = "Recai Oktaş"
id = "roktas"
bio = "Muhayyer Yazılar"
avatar = "/images/roktas.png"
links = [
    { name = "Github", icon = "github", url = "https://github.com/roktas" },
]

homepage_layout = "recent"

recent_max = 15
recent_more = false
recent_more_text = "dahası »"

sections = [
    { name = "0", path = "/0", description = "Genel içerik",  is_external = false },
    { name = "1", path = "/1", description = "Teknik içerik", is_external = false },
    { name = "9", path = "/9", description = "Okuma notları", is_external = false },
]
blog_section_path = "/1"
blog_section_paths = ["/0", "/1", "/9"]

nav_separator = ""
nav_wrapper_left = "{"
nav_wrapper_right = "} ;"
nav_wrapper_separator = ","

display_id = true
blog_categorized = false
blur_effect = true
back_to_top = true

toc = true
copy = true
comment = false
display_tags = true
truncate_summary = false

outdate_alert = false
outdate_alert_days = 120
outdate_alert_text_before = "This article was last updated "
outdate_alert_text_after = " days ago and may be out of date."

footer_copyright = "© 2024 roktas"
footer_credits = false

not_found_title = "404"
not_found_error_text = "Bulunamadı"
not_found_recover_text = "« ön sayfaya dön »"
